name: Experiment

on:
  workflow_dispatch:
    inputs:
      file:
        required: true
        type: string

jobs:

  experiment:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@af83be0ddf1ec3035230c030f3ab6d10a7040515
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: ${{ github.token }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # main
      - if: false
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          touch ${{ inputs.file }}
          if [ -z "$(git status --porcelain)" ]; then exit 0; fi
          if gh api user --jq .id; then
            user_id="$(gh api user --jq .id)"
            user_name="$(gh api user --jq .login)"
          else
            user_name="github-actions[bot]"
            user_id="$(gh api /users/"$user_name" --jq .id)"
          fi
          git config user.name "$user_name"
          git config user.email "${user_id}+${user_name}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git add -A
          git commit -m "experiment"
          git push
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh issue create --title TEST --body test
    permissions:
      actions: read
      contents: write
      issues: write
