name: Experiment

on:
  workflow_dispatch:
    inputs:
      file:
        required: true
        type: string

jobs:

  experiment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: |
          touch ${{ inputs.file }}
          git add -A
          git commit -m "experiment"
          git push
