name: Publish
on:
  push:
    branches: main
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@48918a17e96079ba32d8379d536c89679ab39340 # v5.63.0
        with:
          secrets_to_redact: '["${{ github.token }}","${{secrets.NPM_TOKEN}}"]'
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version: 19
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    permissions:
      actions: read
