name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: renovatebot/github-action@v32.186.1
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
