name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: renovatebot/github-action@v40.1.0
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
