name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: renovatebot/github-action@v40.1.9
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
